extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

test123/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from check import views
from check.views import AddUserAskView,AddSrcView,AddNetView,AddUserAskView1,AddUserAskView2


import xadmin
from django.views.static import serve
from test123 import settings


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='index'),
    url(r'^index_new/$', views.index_new,name='index_new'),
    url('check/$', views.check),
    # url(r'^detail/(?P<system_id>\d+)/$', views.detail),

    url(r'^detail/', views.detail),
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url('checkdevinfo/$', views.checkdevinfo),
    url('checksysinfo/$', views.checksysinfo),
    url('login/$', views.userlogin,name='login'),
    url(r'^logout/$', views.userlogout, name="logout"),
    # url(r'^usercenter-info/$', ss.as_view(), name="usercenter-info"),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),

    url('checkSec/$', views.checkSec),
    url('checkNet/$', views.checkNet),
    url('detail_src/$', views.detail_src),
    url(r'^add_src/$', AddSrcView.as_view(), name="add_src"),
    url('detail_net/$', views.detail_net),
    url(r'^add_net/$', AddNetView.as_view(), name="add_net"),

    url('finish2/$', views.finish2),

    url(r'^add_ask1/$', AddUserAskView1.as_view(), name="add_ask1"),
    url(r'^add_ask2/$', AddUserAskView2.as_view(), name="add_ask2"),
]

users/urls.py
from users.views import UserInfoView,UploadImageView,UpdatePwdView
from django.conf.urls import url,include



urlpatterns = [

    url(r'^usercenter-info/$', UserInfoView.as_view(), name="usercenter-info"),

    # 用户上传头像
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),

    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),
]

check/models.py
from django.db import models
from datetime import datetime
from users.models import Department

class LocationDict(models.Model):
    name = models.CharField(max_length=20, verbose_name=u"机房位置")
    desc = models.CharField(max_length=200, verbose_name=u"描述")
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = u"机房位置说明"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name



class SystemInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"业务系统名称")
    address = models.URLField(max_length=100, verbose_name=u" 业务系统地址")
    details = models.TextField(max_length=1500, verbose_name=u"系统详情")
    admin = models.CharField(max_length=20,verbose_name=u"负责人")
    backups = models.CharField(max_length=10, choices=(("True", "有"), ("Fales", "无")), default="无", verbose_name=u"异机数据备份")
    checkmethod = models.TextField(max_length=2000, verbose_name=u"巡检方法")
    location = models.ForeignKey(LocationDict,on_delete=models.CASCADE, verbose_name=u"机房位置")
    auto_check = models.IntegerField(choices=((1, "是"), (2, "否")), default=2, verbose_name=u"本业务线是否进行自动巡检")

    class Meta:
        verbose_name = u"业务系统信息说明"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name



class Department2System(models.Model):

    d = models.ForeignKey(Department ,on_delete=models.CASCADE, verbose_name=u"巡检科室")
    s = models.ForeignKey(SystemInfo, on_delete=models.CASCADE, verbose_name=u"业务系统")

    class Meta:
        verbose_name = u"组&系统对应关系"
        verbose_name_plural = verbose_name

    # def __str__(self):
    #     return self.name

class ResourceInfo(models.Model):
    resource_name = models.CharField(max_length=50, verbose_name=u"设备名称")
    resource_IP = models.GenericIPAddressField(verbose_name=u"IP地址")
    resource_system = models.ForeignKey(SystemInfo,on_delete=models.CASCADE, verbose_name=u"所属业务系统")
    resource_user = models.CharField(max_length=50,verbose_name=u"巡检账号", null=True, blank=True)
    resource_pwd = models.CharField(max_length=50,verbose_name=u"巡检密码", null=True, blank=True)
    resource_sys = models.IntegerField(choices=((1, "windows"), (2, "linux"),(3,"HP-UX"),(4,'No monitoring')), null=True, blank=True, verbose_name=u"操作系统")
    class Meta:
        verbose_name = u"服务器信息说明"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.resource_name


class UserCheckDev(models.Model):
    user_name = models.CharField(max_length=50, verbose_name=u"巡检人")
    dev_id = models.ForeignKey(ResourceInfo, on_delete=models.CASCADE, verbose_name=u"服务器")
    # isnormal = models.CharField(max_length=10, choices=(("True", "正常"), ("Fales", "故障")), default="True",verbose_name=u"服务器状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"巡检时间")
    ckeckCPU = models.CharField(max_length=50, verbose_name=u"CPU占用率（%）")
    checkMEM = models.CharField(max_length=50, verbose_name=u"内存使用率(%)")
    checkDISK = models.CharField(max_length=50, verbose_name=u"硬盘使用率(%)")
    # checkmiddleware = models.CharField(max_length=10, choices=(("True", "正常"), ("Fales", "故障")), default="True", verbose_name=u"中间件")
    # checkdatabase = models.CharField(max_length=10, choices=(("True", "正常"), ("Fales", "故障")), default="True", verbose_name=u"数据库")
    service = models.IntegerField(choices=((1, "正常"), (2, "故障")), default=1, verbose_name=u"服务和进程状态")
    details = models.TextField(verbose_name=u"故障描述", null=True, blank=True)

    class Meta:
        verbose_name = u"基础设备巡检记录"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __str__(self):
        return self.user_name



class UserCheckSys(models.Model):
    user_name = models.CharField(max_length=50, verbose_name=u"巡检人")
    system_name = models.ForeignKey(SystemInfo, on_delete=models.CASCADE, verbose_name=u" 业务系统")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"巡检时间")
    sysisnormal = models.IntegerField(choices=((1, "正常"), (2, "故障")), default=1, verbose_name=u"是否正常")
    # psef = models.IntegerField(choices=((1, "正常"), (2, "故障")), default=1, verbose_name=u"psef是否正常")
    check_details = models.TextField(verbose_name=u"故障描述", null=True, blank=True)
    details= models.TextField(verbose_name=u"故障描述", null=True, blank=True)

    class Meta:
        verbose_name = u"应用系统巡检记录"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    # def __str__(self):
    #
    #     return str(self.sysisnormal)


# class SecurityDevice(models.Model):
#     SecurityDevice_name = models.CharField(max_length=50, verbose_name=u"安全设备名称")
#     SecurityDevice_IP = models.GenericIPAddressField(verbose_name=u"IP地址")
#     SecurityDevice_brand = models.CharField(max_length=50, verbose_name=u"安全设备品牌")
#     SecurityDevice_pwd = models.CharField(max_length=50,verbose_name=u"巡检密码", null=True, blank=True)
#     auto_check = models.IntegerField(choices=((1, "是"), (2, "否")), default=2, verbose_name=u"安全设备是否进行自动巡检")
#     class Meta:
#         verbose_name = u"安全设备信息1"
#         verbose_name_plural = verbose_name
#
#     def __str__(self):
#         return self.SecurityDevice_name

class  SecurityDevice(models.Model):
    SecurityDevice_name = models.CharField(max_length=50, verbose_name=u"安全设备名称")
    SecurityDevice_IP = models.GenericIPAddressField(verbose_name=u"IP地址")
    SecurityDevice_brand = models.CharField(max_length=50, verbose_name=u"安全设备品牌")
    SecurityDevice_user = models.CharField(max_length=50,verbose_name=u"巡检账号", null=True, blank=True)
    SecurityDevice_pwd = models.CharField(max_length=50,verbose_name=u"巡检密码", null=True, blank=True)
    auto_check = models.IntegerField(choices=((1, "是"), (2, "否")), default=2, verbose_name=u"安全设备是否进行自动巡检")
    class Meta:
        verbose_name = u"安全设备信息说明"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.SecurityDevice_name


class UserCheckSec(models.Model):
    user_name = models.CharField(max_length=50, verbose_name=u"巡检人")
    Sec_id = models.ForeignKey(SecurityDevice, on_delete=models.CASCADE, verbose_name=u"安全设备")
    # isnormal = models.CharField(max_length=10, choices=(("True", "正常"), ("Fales", "故障")), default="True",verbose_name=u"服务器状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"巡检时间")
    ckeckCPU = models.CharField(max_length=50, verbose_name=u"CPU占用率（%）")
    checkMEM = models.CharField(max_length=50, verbose_name=u"内存使用率(%)")
    checkSessionNum = models.CharField(max_length=50, verbose_name=u"会话连接数")
    # checkmiddleware = models.CharField(max_length=10, choices=(("True", "正常"), ("Fales", "故障")), default="True", verbose_name=u"中间件")
    # checkdatabase = models.CharField(max_length=10, choices=(("True", "正常"), ("Fales", "故障")), default="True", verbose_name=u"数据库")
    state = models.IntegerField(choices=((1, "正常"), (2, "故障")), default=1, verbose_name=u"设备状态")
    details = models.TextField(verbose_name=u"备注", null=True, blank=True)

    class Meta:
        verbose_name = u"安全设备巡检记录"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __str__(self):
        return self.user_name


class NetworkDevice(models.Model):
    NetworkDevice_name = models.CharField(max_length=50, verbose_name=u"网络设备名称")
    NetworkDevice_IP = models.GenericIPAddressField(verbose_name=u"IP地址")
    SecurityDevice_user = models.CharField(max_length=50,verbose_name=u"巡检账号", null=True, blank=True)
    SecurityDevice_pwd = models.CharField(max_length=50,verbose_name=u"巡检密码", null=True, blank=True)
    auto_check = models.IntegerField(choices=((1, "是"), (2, "否")), default=2, verbose_name=u"安全设备是否进行自动巡检")
    class Meta:
        verbose_name = u"网络设备信息说明"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.NetworkDevice_name


class UserCheckNet(models.Model):
    user_name = models.CharField(max_length=50, verbose_name=u"巡检人")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"巡检时间")
    Net_id = models.ForeignKey(NetworkDevice, on_delete=models.CASCADE, verbose_name=u"网络设备")
    UpstreamBandwidth = models.CharField(max_length=50, verbose_name=u"上行带宽",null=True, blank=True)
    DownstreamBandwidth=  models.CharField(max_length=50, verbose_name=u"下行带宽",null=True, blank=True)
    details = models.TextField(verbose_name=u"备注", null=True, blank=True)
    class Meta:
        verbose_name = u"网络设备巡检记录"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __str__(self):
        return self.user_name


class UserCheckNetSys(models.Model):
    user_name = models.CharField(max_length=50, verbose_name=u"巡检人")
    # Net_id = models.ForeignKey(NetworkDevice, on_delete=models.CASCADE, verbose_name=u"网络设备")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"巡检时间")
    CoreSwitch =  models.TextField(verbose_name=u"核心交换机状态")
    ConvergingSwitch=   models.TextField(verbose_name=u"汇聚交换机状态" )
    details = models.TextField(verbose_name=u"无线设备状态", null=True, blank=True)
    class Meta:
        verbose_name = u"交换机巡检记录"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __str__(self):
        return self.user_name

templates/check.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}巡检{% endblock %}
{% block custom_css %}
     <link href="{% static 'css/pricing.css' %}" rel="stylesheet" />
        <style>
        .hide{
           display:none;
         }
        .c1{
            position: fixed;
            left: 0;
            top:0;
            right: 0;
            bottom: 0;
            background-color: black;
            opacity: 0.6;
            z-index: 9 ;
        }
        .c2{
            width: 1000px;
            height: 800px;
            background-color: white;
            position: fixed;
            left: 20%;
            top:50%;
            margin-left: 250px;
            margin-top:-500px;
            z-index: 10;
        }

    </style>
{% endblock %}

{% block menu_active %}
<li>
<a href="/"><i class="fa fa-dashboard "></i>首页</a>
</li>
<li>
<a class="active-menu" href="/check/"><i class="fa fa-eyedropper "></i>巡检</a>
</li>
</li>
<li>
<a href="/checksysinfo/"><i class="fa fa-eyedropper "></i>最新系统状态</a>
</li>
<li>
<a href="/checkdevinfo/"><i class="fa fa-eyedropper "></i>最新服务器状态</a>
</li>
<li>
{#<a href="#"><i class="fa fa-sitemap "></i>业务系统信息 <span class="fa arrow"></span></a>#}
{# <ul class="nav nav-second-level">#}
{#     {% for systems in all_system %}#}
{#         <li>#}
{#        <a href="#"><i class="fa fa-flask "></i>{{ systems.name }}</a>#}
{#    </li>#}
{#     {% endfor %}#}
{##}
{#</ul>#}

{% endblock %}




{% block page-wrapper %}
             <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">日常巡检---{{ department_name }}</h1>
                        <h1 class="page-subhead-line">按系统巡检进行每日巡检 </h1>

                    </div>
                        <div class="row text-center pad-row">
                            {% for systems in all_system %}
                <div class="col-md-3">
                    <div class="panel-info simple-table">
                        <div class="panel-heading">
                            <h4><strong> {{ systems.name }}</strong></h4>
                        </div>
                        <div class="alert alert-info">

                            <ul class="plan" >
                                <li ><strong ><a target="_blank" href="{{ systems.address }}">{{ systems.address }}</a></strong ></li>
                                <li>服务器<strong>{{ systems.resourceinfo_set.count }}</strong>台</li>
                                <li>负责人：<strong>{{ systems.admin }}</strong> </li>
{#                                   {% for row in chech_t %}#}


{#                                <li>最后巡检时间：<strong>{{  systems.add_time }}</strong> </li>#}
{#                                         {% endfor %}#}
                            </ul>
{#                            <input type="button" value="巡检"  onclick="ShowModel();" href="#" class="btn btn-danger "></input>#}
                           <a target="_blank" value="巡检" href="/detail/?nid={{ systems.id }}" class="btn btn-danger ">巡检</a>
{#                            <a href="{% url 'check_home'{{ systems.id  }} %}">#}
                        </div>

                    </div>
                </div>
                            {% endfor %}


            </div>

                     <!--遮罩层开始 -->
                            <div id="i1"class="c1 hide" ></div>
                    <!--遮罩层结束 -->
                    <!--弹出框开始 -->

                            <dev id="i2"class="c2 hide" >

   <div class="col-md-11">
                  <!--   Kitchen Sink -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {{ systems.name }}
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>服务器名称</th>
                                            <th>IP</th>
                                            <th>CPU占用率(%)</th>
                                            <th>内存使用率(%)</th>
                                            <th>硬盘使用率(%)</th>
                                            <th>中间件</th>
                                            <th>数据库</th>
                                           <th> 故障描述</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>@fat</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>@twitter</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                            <td>@mdo</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                                <input type="text" value="xitong">
                                <input type="text" value="xitong">
                                <input type="text" value="xitong">
                                <input type="" value="xitong">
                                <input textarea> </input textarea>


                               <p><input type="button" value="取消" onclick="HideModel();"></p>
                            <p><input type="button" value="确定"></p>

                    </div>
                     <!-- End  Kitchen Sink -->


    </div>
                    <!--弹出框结束 -->

  </dev>

                <!-- /. ROW  -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-info">
                            This is a free responsive admin under cc3.0 license, so you can use it for personal and commercial use.
                          <br />
                            Enjoy this admin and for more please keep looking <a href="http://www.binarytheme.com/" target="_blank">BinaryTheme.com</a>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /. PAGE INNER  -->
        </div>

{% endblock %}

{% block custom_js %}
        <script>
        function ShowModel() {
            document.getElementById('i1').classList.remove('hide')
            document.getElementById('i2').classList.remove('hide')
        }
                function HideModel() {
            document.getElementById('i1').classList.add('hide')
            document.getElementById('i2').classList.add('hide')
        }
    </script>
{% endblock %}

templates/checkdevinfo.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}服务器状态{% endblock %}
{% block custom_css %}

{% endblock %}


{% block menu_active %}
<li>
<a href="/"><i class="fa fa-dashboard "></i>首页</a>
</li>
<li>
<a href="/check/"><i class="fa fa-eyedropper "></i>巡检</a>
</li>
</li>
<li>
<a href="/checksysinfo/"><i class="fa fa-eyedropper "></i>最新系统状态</a>
</li>
<li>
<a class="active-menu" href="/checkdevinfo/"><i class="fa fa-eyedropper "></i>最新服务器状态</a>
</li>
<li>
{#<a href="#"><i class="fa fa-sitemap "></i>业务系统信息 <span class="fa arrow"></span></a>#}
{# <ul class="nav nav-second-level">#}
{#     {% for systems in all_system %}#}
{#         <li>#}
{#        <a href="#"><i class="fa fa-flask "></i>{{ systems.name }}</a>#}
{#    </li>#}
{#     {% endfor %}#}
{##}
{#</ul>#}

{% endblock %}



{% block page-wrapper %}
      <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">最新服务器状态</h1>
                        <h1 class="page-subhead-line">最近一次巡检的服务器状态 </h1>

                    </div>
                </div>
                <!-- /. ROW  -->
                <div class="row">

                </div>
                <!-- /. ROW  -->
                 <div class="row">
                   <div class="col-md-12">
                       <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">服务器列表</div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
              <th>所属业务系统</th>
              <th>服务器名称</th>
              <th>IP</th>
              <th>巡检时间</th>
            <th>巡检人</th>
            <th>CPU</th>
            <th>内存</th>
            <th>硬盘</th>
              <th>服务和进程状态</th>

            <th>备注</th>
          </tr>
        </thead>
        <tbody>
            {% for row in dev_check_new %}
                      <tr class="list-group-item-success">
                      <td>{{  forloop.counter }}</td>
                      <th>{{ row.name }}</th>
                      <td>{{ row.dev_id }}</td>
                      <td>{{ row.dev_id.resource_IP}}</td>
                      <td>{{ row.add_time }}</td>
                      <td>{{ row.user_name }}</td>
                      <td>{{ row.ckeckCPU }}</td>
                      <td>{{ row.checkMEM }}</td>
                      <td>{{ row.checkDISK }}</td>
                          <td><span name="status" class="label label-info">{{ row.get_service_display }}</span></td>
                      <td>{{ row.details }}</td>

          </tr>
            {% endfor %}


        </tbody>
      </table>
    </div>
                   </div>
                     </div>
            </div>
{% endblock %}

{% block custom_js %}
<script>
    tag = document.getElementsByName('status')
    for(var i in tag){
        if(tag[i].innerText=='故障'){
            tag[i].className='label label-danger'
        }
    }
    </script>
{% endblock %}

templates/usercenter-info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}个人中心{% endblock %}


{% block menu_active %}
<li>
<a class="active-menu" href="/"><i class="fa fa-dashboard "></i>首页</a>
</li>
<li>
<a href="/check/"><i class="fa fa-eyedropper "></i>巡检</a>
</li>
</li>
<li>
<a href="/checksysinfo/"><i class="fa fa-eyedropper "></i>最新系统状态</a>
</li>
<li>
<a href="/checkdevinfo/"><i class="fa fa-eyedropper "></i>最新服务器状态</a>
</li>
<li>
<a href="#"><i class="fa fa-sitemap "></i>业务系统信息 <span class="fa arrow"></span></a>
 <ul class="nav nav-second-level">
     {% for systems in all_system %}
         <li>
        <a href="#"><i class="fa fa-flask "></i>{{ systems.name }}</a>
    </li>
     {% endfor %}

</ul>

{% endblock %}

{% block page-wrapper %}
<div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">个人中心</h1>
                        <h1 class="page-subhead-line">更换头像和密码</h1>

                    </div>
                </div>
                <!-- /. ROW  -->
                <div class="row">
                               <div class="col-md-6">
                       <div class="panel panel-default">
                        <div class="panel-heading">
                          更换头像
                        </div>
                        <div class="panel-body">


                    <div style="height: 400px" class="form-group" >
                        <label class="control-label col-lg-4">Pre Defined Image</label>
                        <div class="">
{#                            <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>#}
                             <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="{% static 'img/demoUpload.jpg'%}" alt="" /></div>
                                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                <div>
                                    <span class="btn btn-file btn-primary"><span class="fileupload-new">选择本地头像</span><span class="fileupload-exists">更换</span><input type="file" name="image" class="js-imp-up"></span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">删除</a>
                                </div>
                            </div>
                                           <button type="submit" class="btn btn-info">更换头像</button>
                                         {% csrf_token %}
                                 </form>
                        </div>
                    </div>
                    <div class="alert alert-warning"><strong>Notice!</strong> Image preview only works in IE10+, FF3.6+, Chrome6.0+ and Opera11.1+. In older browsers and Safari, the filename is shown instead.</div>
                    </div>
                           </div>
                                                  <div class="panel panel-default">
                        <div class="panel-heading">
                          修改密码
                        </div>
                        <div class="panel-body">
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>

                    <div style="height: 400px" class="form-group form-control" >
  <div class="resetpwdbox dialogbox" id="jsResetDialog">
                        <h1>修改密码</h1>
        <div class="close jsCloseDialog"></div>
        <div class="cont">
            <form id="jsResetPwdForm" autocomplete="off">
                <div class="box">
                    <label class="word2" >新&nbsp;&nbsp;密&nbsp;&nbsp;码</label>
                    <input class="form-control" type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                </div>
                <div class="box">
                    <label class="word2" >确定密码</label>
                    <input class="form-control" type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                </div>
                <div class="error btns alert-danger alert-dismissable" id="jsResetPwdTips"></div>
                <div  class="col-md-6 col-sm-6 col-xs-12" class="button">
                <br>
                    <br>
                    <input class="btn btn-info"  id="jsResetPwdBtn" type="button" value="提交" />
                </div>
                <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP' />
            <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                {% csrf_token %}
            </form>
        </div>
       </div>
                    </div>
                    <div class="alert alert-warning"><strong>Notice!</strong> Image preview only works in IE10+, FF3.6+, Chrome6.0+ and Opera11.1+. In older browsers and Safari, the filename is shown instead.</div>
                    </div>
                           </div>
                        </div>

                </div>

            </div>










{% endblock %}






    {% block custom_js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/deco-user.js' %}"></script>
    <script src="{% static 'js/deco-common.js' %}"></script>

        {% endblock %}